# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v4

    - id: setup-chrome
      name: Setup Chromium
      uses: browser-actions/setup-chrome@v1

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Set chrome path
      run: echo "CHROME=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - id: 'glcoud-auth'
      name: Setup GCloud Auth
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: 'projects/76184862476/locations/global/workloadIdentityPools/main-pool/providers/github'
        service_account: '76184862476-compute@developer.gserviceaccount.com'

    - name: 'Set up GCloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
